package IOXOxOII;

import OXOo.OOXIXo;
import android.os.Parcel;
import kotlin.NotImplementedError;

/* loaded from: classes6.dex */
public interface II0xO0<T> {

    /* loaded from: classes6.dex */
    public static final class oIX0oI {
        @OOXIXo
        public static <T> T[] oIX0oI(@OOXIXo II0xO0<T> iI0xO0, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    void II0xO0(T t, @OOXIXo Parcel parcel, int i);

    @OOXIXo
    T[] newArray(int i);

    T oIX0oI(@OOXIXo Parcel parcel);
}
