package com.baidu.mapframework.nirvana.module;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'UNDEFINED_MODULE' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByRegister(EnumVisitor.java:395)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:324)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* loaded from: classes7.dex */
public final class Module {
    public static final Module ACCOUNT_MODULE;
    public static final Module ADVERT_CTRL_MODULE;
    public static final Module AIME_MODULE;
    public static final Module AI_HOME_MODULE;
    public static final Module AI_TRAVEL;
    public static final Module ALL_DU_ENTRANCE;
    public static final Module BASE_FRAMEWORK_MODULE;
    public static final Module BASE_MAPVIEW_MODULE;
    public static final Module BLUE_TOOTH_MODULE;
    public static final Module BMES_MODULE;
    public static final Module BN_HOME_COMPANY_MODULE;
    public static final Module BRAAVOS_MODULE;
    public static final Module BRAND_MODULE;
    public static final Module BUS_ARRIVAL_REMIND_MODULE;
    public static final Module BUS_SCREENSHOT_MODULE;
    public static final Module CAR_OWNER;
    public static final Module CLOUD_CONTROL_MODULE;
    public static final Module COACH_MODULE;
    public static final Module COMMON_WIDGET_MODULE;
    public static final Module COM_PLATFORM_MODULE;
    public static final Module DEFAULT_MAP_LAYOUT_MODULE;
    public static final Module DRIVE_MODULE;
    public static final Module DU_HELPER_MODULE;
    public static final Module ENTRY_CONTROLLER_MODULE;
    public static final Module EVENTBUS_MODULE;
    public static final Module FAST_NAVI_MODULE;
    public static final Module FAVORITE_MODULE;
    public static final Module FLIGHT_MODULE;
    public static final Module GLIDE_MODULE;
    public static final Module GLOBAL_TRAVEL_MODULE;
    public static final Module HOTSPOT_MODULE;
    public static final Module HOT_WORD_MODULE;
    public static final Module INDOOR_GUARD_MODULE;
    public static final Module INDOOR_MODULE;
    public static final Module INTERNATIONAL_MODULE;
    public static final Module LAYER_ACTION_MODULE;
    public static final Module LAYOUT_AUTO;
    public static final Module LIVE_ROOM_MODULE;
    public static final Module LOCAL_MAP_MODULE;
    public static final Module LOCATION_MODULE;
    public static final Module LOC_SHARE_MODULE;
    public static final Module LOG_STATISTICS_MODULE;
    public static final Module MAP_ACTIVITY_MODULE;
    public static final Module MAP_APPLICARION_MODULE;
    public static final Module MAP_ENGINE;
    public static final Module MAP_FRAME_MODULE;
    public static final Module MATERIAL_CENTER_MODULE;
    public static final Module MESSAGE_MODULE;
    public static final Module MONITOR_MODULE;
    public static final Module MTJ;
    public static final Module MYLOCATION_MODULE;
    public static final Module MY_MAP_MODULE;
    public static final Module NAV_DATA_MODULE;
    public static final Module NAV_MODULE;
    public static final Module NAV_TTS_MODULE;
    public static final Module NA_CRASH_MODULE;
    public static final Module NEARBY_HOT_WORD_MODULE;
    public static final Module NEARBY_MODULE;
    public static final Module NETWORK_DETECT;
    public static final Module NUOMI_HYBRID_MODULE;
    public static final Module OEM_MODULE;
    public static final Module OPENPI_MODULE;
    public static final Module OPEN_SERVICE_MODULE;
    public static final Module OPERATION_MAP_MODULE;
    public static final Module OPERATION_MODULE;
    public static final Module PANO_MODULE;
    public static final Module PATCH_MODULE;
    public static final Module POI_DETAIL_MODULE;
    public static final Module POI_LIST_MODULE;
    public static final Module POI_PLACE_MODULE;
    public static final Module POI_SEARCH_MODULE;
    public static final Module PUSH_MODULE;
    public static final Module QA_FRAMEWORK_MODULE;
    public static final Module RECOMMEND_MODULE;
    public static final Module RENT_CAR;
    public static final Module ROAD_CONDITION_MODULE;
    public static final Module ROAD_CONDITION_VIDEO_MODULE;
    public static final Module ROAM_INFO_MODULE;
    public static final Module ROUTE_BIKE_WALK_MODULE;
    public static final Module ROUTE_BUS_MODULE;
    public static final Module ROUTE_CAR_MODULE;
    public static final Module ROUTE_DEFAULT_MAP_LAYOUT_MODULE;
    public static final Module ROUTE_MODULE;
    public static final Module ROUTE_MOTOR_MODULE;
    public static final Module ROUTE_REALTIME_MODULE;
    public static final Module ROUTE_TRUCK_MODULE;
    public static final Module SAND_BOX_MODULE;
    public static final Module SAPI_MODULE;
    public static final Module SCENERY_MODULE;
    public static final Module SEARCH_FRAMEWORK_MODULE;
    public static final Module SEARCH_NEARBY_MODULE;
    public static final Module SECURE_MODULE;
    public static final Module SELECT_POINT_MODULE;
    public static final Module SENSOR_MODULE;
    public static final Module SETTING_MODULE;
    public static final Module SHARE_BIKE;
    public static final Module SHARE_MODULE;
    public static final Module SIRI_MODULE;
    public static final Module SKIN_MODULE;
    public static final Module STREET_SCAPE_MODULE;
    public static final Module SUBWAY_STATION_DETAIL_MODULE;
    public static final Module SYNC_MODULE;
    public static final Module TRACK_MODULE;
    public static final Module TRAVEL_ASSISTANT_MODULE;
    public static final Module TRAVEL_EXPLORER_MODULE;
    public static final Module UGC_REPORT_MODULE;
    public static final Module UNDEFINED_MODULE;
    public static final Module UNFINISHED_MODULE;
    public static final Module UNIVERSAL_LAYER_MODULE;
    public static final Module UPLOAD_PIC_MODULE;
    public static final Module USER_CENTER_MODULE;
    public static final Module USER_GUIDE_MODULE;
    public static final Module VERSION_UPDATE_MODULE;
    public static final Module VIDEO_UPLOAD_MODULE;
    public static final Module VOICE_COMPONENT_MODULE;
    public static final Module VOICE_INIT_MODULE;
    public static final Module VOICE_MODULE;
    public static final Module WALLET_MODULE;
    public static final Module WEATHER_MODULE;
    public static final Module WEB_SDK_MODULE;
    public static final Module WELCOME_MODULE;
    public static final Module WIFITRANSFER_MODULE;
    public static final Module WIFI_MODULE;
    public static final Module YELLOW_BANNER_MODULE;
    public static final Module ZOOM_ACTION_MODULE;
    private static final /* synthetic */ Module[] b;

    /* renamed from: a, reason: collision with root package name */
    private final ModuleType f6102a;

    static {
        ModuleType moduleType = ModuleType.UNDEFINED;
        Module module = new Module("UNDEFINED_MODULE", 0, moduleType);
        UNDEFINED_MODULE = module;
        Module module2 = new Module("UNFINISHED_MODULE", 1, moduleType);
        UNFINISHED_MODULE = module2;
        ModuleType moduleType2 = ModuleType.DATA_MODULE;
        Module module3 = new Module("AI_HOME_MODULE", 2, moduleType2);
        AI_HOME_MODULE = module3;
        Module module4 = new Module("BASE_FRAMEWORK_MODULE", 3, moduleType2);
        BASE_FRAMEWORK_MODULE = module4;
        Module module5 = new Module("QA_FRAMEWORK_MODULE", 4, moduleType2);
        QA_FRAMEWORK_MODULE = module5;
        Module module6 = new Module("EVENTBUS_MODULE", 5, moduleType2);
        EVENTBUS_MODULE = module6;
        Module module7 = new Module("COM_PLATFORM_MODULE", 6, moduleType2);
        COM_PLATFORM_MODULE = module7;
        Module module8 = new Module("SAND_BOX_MODULE", 7, moduleType2);
        SAND_BOX_MODULE = module8;
        ModuleType moduleType3 = ModuleType.UI_MODULE;
        Module module9 = new Module("MAP_ENGINE", 8, moduleType3);
        MAP_ENGINE = module9;
        Module module10 = new Module("NAV_MODULE", 9, moduleType3);
        NAV_MODULE = module10;
        Module module11 = new Module("NAV_TTS_MODULE", 10, moduleType3);
        NAV_TTS_MODULE = module11;
        Module module12 = new Module("NAV_DATA_MODULE", 11, moduleType2);
        NAV_DATA_MODULE = module12;
        Module module13 = new Module("POI_DETAIL_MODULE", 12, moduleType3);
        POI_DETAIL_MODULE = module13;
        Module module14 = new Module("POI_LIST_MODULE", 13, moduleType3);
        POI_LIST_MODULE = module14;
        Module module15 = new Module("POI_SEARCH_MODULE", 14, moduleType3);
        POI_SEARCH_MODULE = module15;
        Module module16 = new Module("SUBWAY_STATION_DETAIL_MODULE", 15, moduleType3);
        SUBWAY_STATION_DETAIL_MODULE = module16;
        Module module17 = new Module("MAP_APPLICARION_MODULE", 16, moduleType3);
        MAP_APPLICARION_MODULE = module17;
        Module module18 = new Module("MAP_ACTIVITY_MODULE", 17, moduleType3);
        MAP_ACTIVITY_MODULE = module18;
        Module module19 = new Module("ENTRY_CONTROLLER_MODULE", 18, moduleType3);
        ENTRY_CONTROLLER_MODULE = module19;
        Module module20 = new Module("MAP_FRAME_MODULE", 19, moduleType3);
        MAP_FRAME_MODULE = module20;
        Module module21 = new Module("NEARBY_MODULE", 20, moduleType3);
        NEARBY_MODULE = module21;
        Module module22 = new Module("USER_CENTER_MODULE", 21, moduleType3);
        USER_CENTER_MODULE = module22;
        Module module23 = new Module("MESSAGE_MODULE", 22, moduleType3);
        MESSAGE_MODULE = module23;
        Module module24 = new Module("ROUTE_CAR_MODULE", 23, moduleType3);
        ROUTE_CAR_MODULE = module24;
        Module module25 = new Module("ROUTE_BUS_MODULE", 24, moduleType3);
        ROUTE_BUS_MODULE = module25;
        Module module26 = new Module("ROUTE_REALTIME_MODULE", 25, moduleType3);
        ROUTE_REALTIME_MODULE = module26;
        Module module27 = new Module("ROUTE_BIKE_WALK_MODULE", 26, moduleType3);
        ROUTE_BIKE_WALK_MODULE = module27;
        Module module28 = new Module("BUS_ARRIVAL_REMIND_MODULE", 27, moduleType3);
        BUS_ARRIVAL_REMIND_MODULE = module28;
        Module module29 = new Module("FAVORITE_MODULE", 28, moduleType3);
        FAVORITE_MODULE = module29;
        Module module30 = new Module("LOCAL_MAP_MODULE", 29, moduleType3);
        LOCAL_MAP_MODULE = module30;
        Module module31 = new Module("GLIDE_MODULE", 30, moduleType3);
        GLIDE_MODULE = module31;
        Module module32 = new Module("DEFAULT_MAP_LAYOUT_MODULE", 31, moduleType3);
        DEFAULT_MAP_LAYOUT_MODULE = module32;
        Module module33 = new Module("BASE_MAPVIEW_MODULE", 32, moduleType3);
        BASE_MAPVIEW_MODULE = module33;
        Module module34 = new Module("SIRI_MODULE", 33, moduleType3);
        SIRI_MODULE = module34;
        Module module35 = new Module("VERSION_UPDATE_MODULE", 34, moduleType3);
        VERSION_UPDATE_MODULE = module35;
        Module module36 = new Module("OPENPI_MODULE", 35, moduleType3);
        OPENPI_MODULE = module36;
        Module module37 = new Module("SETTING_MODULE", 36, moduleType3);
        SETTING_MODULE = module37;
        Module module38 = new Module("ROAD_CONDITION_VIDEO_MODULE", 37, moduleType3);
        ROAD_CONDITION_VIDEO_MODULE = module38;
        Module module39 = new Module("COMMON_WIDGET_MODULE", 38, moduleType3);
        COMMON_WIDGET_MODULE = module39;
        Module module40 = new Module("ALL_DU_ENTRANCE", 39, moduleType3);
        ALL_DU_ENTRANCE = module40;
        Module module41 = new Module("LOCATION_MODULE", 40, moduleType2);
        LOCATION_MODULE = module41;
        Module module42 = new Module("HOT_WORD_MODULE", 41, moduleType2);
        HOT_WORD_MODULE = module42;
        Module module43 = new Module("NEARBY_HOT_WORD_MODULE", 42, moduleType2);
        NEARBY_HOT_WORD_MODULE = module43;
        Module module44 = new Module("LOG_STATISTICS_MODULE", 43, moduleType2);
        LOG_STATISTICS_MODULE = module44;
        Module module45 = new Module("MATERIAL_CENTER_MODULE", 44, moduleType2);
        MATERIAL_CENTER_MODULE = module45;
        Module module46 = new Module("SKIN_MODULE", 45, moduleType2);
        SKIN_MODULE = module46;
        Module module47 = new Module("YELLOW_BANNER_MODULE", 46, moduleType2);
        YELLOW_BANNER_MODULE = module47;
        Module module48 = new Module("PUSH_MODULE", 47, moduleType2);
        PUSH_MODULE = module48;
        Module module49 = new Module("ROAM_INFO_MODULE", 48, moduleType2);
        ROAM_INFO_MODULE = module49;
        Module module50 = new Module("VOICE_MODULE", 49, moduleType2);
        VOICE_MODULE = module50;
        ModuleType moduleType4 = ModuleType.COMPONENT;
        Module module51 = new Module("VOICE_COMPONENT_MODULE", 50, moduleType4);
        VOICE_COMPONENT_MODULE = module51;
        Module module52 = new Module("ADVERT_CTRL_MODULE", 51, moduleType4);
        ADVERT_CTRL_MODULE = module52;
        Module module53 = new Module("INDOOR_MODULE", 52, moduleType3);
        INDOOR_MODULE = module53;
        Module module54 = new Module("LAYER_ACTION_MODULE", 53, moduleType3);
        LAYER_ACTION_MODULE = module54;
        Module module55 = new Module("UGC_REPORT_MODULE", 54, moduleType2);
        UGC_REPORT_MODULE = module55;
        Module module56 = new Module("VIDEO_UPLOAD_MODULE", 55, moduleType2);
        VIDEO_UPLOAD_MODULE = module56;
        Module module57 = new Module("ACCOUNT_MODULE", 56, moduleType2);
        ACCOUNT_MODULE = module57;
        Module module58 = new Module("NA_CRASH_MODULE", 57, moduleType2);
        NA_CRASH_MODULE = module58;
        Module module59 = new Module("SENSOR_MODULE", 58, moduleType2);
        SENSOR_MODULE = module59;
        Module module60 = new Module("CLOUD_CONTROL_MODULE", 59, moduleType2);
        CLOUD_CONTROL_MODULE = module60;
        Module module61 = new Module("MYLOCATION_MODULE", 60, moduleType2);
        MYLOCATION_MODULE = module61;
        Module module62 = new Module("BUS_SCREENSHOT_MODULE", 61, moduleType2);
        BUS_SCREENSHOT_MODULE = module62;
        Module module63 = new Module("SECURE_MODULE", 62, moduleType2);
        SECURE_MODULE = module63;
        Module module64 = new Module("SYNC_MODULE", 63, moduleType2);
        SYNC_MODULE = module64;
        Module module65 = new Module("BMES_MODULE", 64, moduleType2);
        BMES_MODULE = module65;
        Module module66 = new Module("WEATHER_MODULE", 65, moduleType2);
        WEATHER_MODULE = module66;
        Module module67 = new Module("UPLOAD_PIC_MODULE", 66, moduleType2);
        UPLOAD_PIC_MODULE = module67;
        Module module68 = new Module("POI_PLACE_MODULE", 67, moduleType3);
        POI_PLACE_MODULE = module68;
        Module module69 = new Module("RECOMMEND_MODULE", 68, moduleType2);
        RECOMMEND_MODULE = module69;
        Module module70 = new Module("SEARCH_FRAMEWORK_MODULE", 69, moduleType2);
        SEARCH_FRAMEWORK_MODULE = module70;
        Module module71 = new Module("PATCH_MODULE", 70, moduleType2);
        PATCH_MODULE = module71;
        Module module72 = new Module("LOC_SHARE_MODULE", 71, moduleType4);
        LOC_SHARE_MODULE = module72;
        Module module73 = new Module("TRACK_MODULE", 72, moduleType4);
        TRACK_MODULE = module73;
        Module module74 = new Module("TRAVEL_EXPLORER_MODULE", 73, moduleType3);
        TRAVEL_EXPLORER_MODULE = module74;
        Module module75 = new Module("STREET_SCAPE_MODULE", 74, moduleType3);
        STREET_SCAPE_MODULE = module75;
        Module module76 = new Module("ZOOM_ACTION_MODULE", 75, moduleType3);
        ZOOM_ACTION_MODULE = module76;
        Module module77 = new Module("LIVE_ROOM_MODULE", 76, moduleType4);
        LIVE_ROOM_MODULE = module77;
        Module module78 = new Module("TRAVEL_ASSISTANT_MODULE", 77, moduleType4);
        TRAVEL_ASSISTANT_MODULE = module78;
        Module module79 = new Module("OPERATION_MODULE", 78, moduleType4);
        OPERATION_MODULE = module79;
        Module module80 = new Module("WIFI_MODULE", 79, moduleType4);
        WIFI_MODULE = module80;
        Module module81 = new Module("PANO_MODULE", 80, moduleType4);
        PANO_MODULE = module81;
        Module module82 = new Module("SCENERY_MODULE", 81, moduleType4);
        SCENERY_MODULE = module82;
        Module module83 = new Module("INDOOR_GUARD_MODULE", 82, moduleType4);
        INDOOR_GUARD_MODULE = module83;
        Module module84 = new Module("BRAND_MODULE", 83, moduleType4);
        BRAND_MODULE = module84;
        Module module85 = new Module("DRIVE_MODULE", 84, moduleType4);
        DRIVE_MODULE = module85;
        Module module86 = new Module("CAR_OWNER", 85, moduleType4);
        CAR_OWNER = module86;
        Module module87 = new Module("RENT_CAR", 86, moduleType4);
        RENT_CAR = module87;
        Module module88 = new Module("AI_TRAVEL", 87, moduleType4);
        AI_TRAVEL = module88;
        Module module89 = new Module("SHARE_BIKE", 88, moduleType4);
        SHARE_BIKE = module89;
        Module module90 = new Module("BRAAVOS_MODULE", 89, moduleType4);
        BRAAVOS_MODULE = module90;
        Module module91 = new Module("INTERNATIONAL_MODULE", 90, moduleType4);
        INTERNATIONAL_MODULE = module91;
        ModuleType moduleType5 = ModuleType.THIRD_SDK;
        Module module92 = new Module("WALLET_MODULE", 91, moduleType5);
        WALLET_MODULE = module92;
        Module module93 = new Module("WEB_SDK_MODULE", 92, moduleType5);
        WEB_SDK_MODULE = module93;
        Module module94 = new Module("SAPI_MODULE", 93, moduleType5);
        SAPI_MODULE = module94;
        Module module95 = new Module("ROUTE_MODULE", 94, moduleType3);
        ROUTE_MODULE = module95;
        Module module96 = new Module("ROUTE_DEFAULT_MAP_LAYOUT_MODULE", 95, moduleType3);
        ROUTE_DEFAULT_MAP_LAYOUT_MODULE = module96;
        Module module97 = new Module("SHARE_MODULE", 96, moduleType3);
        SHARE_MODULE = module97;
        Module module98 = new Module("ROAD_CONDITION_MODULE", 97, moduleType3);
        ROAD_CONDITION_MODULE = module98;
        Module module99 = new Module("SELECT_POINT_MODULE", 98, moduleType3);
        SELECT_POINT_MODULE = module99;
        Module module100 = new Module("OPERATION_MAP_MODULE", 99, moduleType3);
        OPERATION_MAP_MODULE = module100;
        Module module101 = new Module("MY_MAP_MODULE", 100, moduleType3);
        MY_MAP_MODULE = module101;
        Module module102 = new Module("NUOMI_HYBRID_MODULE", 101, moduleType5);
        NUOMI_HYBRID_MODULE = module102;
        Module module103 = new Module("VOICE_INIT_MODULE", 102, moduleType5);
        VOICE_INIT_MODULE = module103;
        Module module104 = new Module("DU_HELPER_MODULE", 103, moduleType3);
        DU_HELPER_MODULE = module104;
        Module module105 = new Module("NETWORK_DETECT", 104, moduleType2);
        NETWORK_DETECT = module105;
        Module module106 = new Module("AIME_MODULE", 105, moduleType2);
        AIME_MODULE = module106;
        Module module107 = new Module("WIFITRANSFER_MODULE", 106, moduleType3);
        WIFITRANSFER_MODULE = module107;
        Module module108 = new Module("MTJ", 107, moduleType5);
        MTJ = module108;
        Module module109 = new Module("MONITOR_MODULE", 108, moduleType2);
        MONITOR_MODULE = module109;
        Module module110 = new Module("LAYOUT_AUTO", 109, moduleType3);
        LAYOUT_AUTO = module110;
        Module module111 = new Module("SEARCH_NEARBY_MODULE", 110, moduleType3);
        SEARCH_NEARBY_MODULE = module111;
        Module module112 = new Module("HOTSPOT_MODULE", 111, moduleType2);
        HOTSPOT_MODULE = module112;
        Module module113 = new Module("USER_GUIDE_MODULE", 112, moduleType3);
        USER_GUIDE_MODULE = module113;
        Module module114 = new Module("BLUE_TOOTH_MODULE", 113, moduleType2);
        BLUE_TOOTH_MODULE = module114;
        Module module115 = new Module("UNIVERSAL_LAYER_MODULE", 114, moduleType3);
        UNIVERSAL_LAYER_MODULE = module115;
        Module module116 = new Module("FLIGHT_MODULE", 115, moduleType3);
        FLIGHT_MODULE = module116;
        Module module117 = new Module("COACH_MODULE", 116, moduleType3);
        COACH_MODULE = module117;
        Module module118 = new Module("ROUTE_MOTOR_MODULE", 117, moduleType3);
        ROUTE_MOTOR_MODULE = module118;
        Module module119 = new Module("ROUTE_TRUCK_MODULE", 118, moduleType3);
        ROUTE_TRUCK_MODULE = module119;
        Module module120 = new Module("GLOBAL_TRAVEL_MODULE", 119, moduleType3);
        GLOBAL_TRAVEL_MODULE = module120;
        Module module121 = new Module("BN_HOME_COMPANY_MODULE", 120, moduleType3);
        BN_HOME_COMPANY_MODULE = module121;
        Module module122 = new Module("OPEN_SERVICE_MODULE", 121, moduleType2);
        OPEN_SERVICE_MODULE = module122;
        Module module123 = new Module("OEM_MODULE", 122, moduleType3);
        OEM_MODULE = module123;
        Module module124 = new Module("FAST_NAVI_MODULE", 123, moduleType3);
        FAST_NAVI_MODULE = module124;
        Module module125 = new Module("WELCOME_MODULE", 124, moduleType3);
        WELCOME_MODULE = module125;
        b = new Module[]{module, module2, module3, module4, module5, module6, module7, module8, module9, module10, module11, module12, module13, module14, module15, module16, module17, module18, module19, module20, module21, module22, module23, module24, module25, module26, module27, module28, module29, module30, module31, module32, module33, module34, module35, module36, module37, module38, module39, module40, module41, module42, module43, module44, module45, module46, module47, module48, module49, module50, module51, module52, module53, module54, module55, module56, module57, module58, module59, module60, module61, module62, module63, module64, module65, module66, module67, module68, module69, module70, module71, module72, module73, module74, module75, module76, module77, module78, module79, module80, module81, module82, module83, module84, module85, module86, module87, module88, module89, module90, module91, module92, module93, module94, module95, module96, module97, module98, module99, module100, module101, module102, module103, module104, module105, module106, module107, module108, module109, module110, module111, module112, module113, module114, module115, module116, module117, module118, module119, module120, module121, module122, module123, module124, module125};
    }

    private Module(String str, int i, ModuleType moduleType) {
        this.f6102a = moduleType;
    }

    public static Module valueOf(String str) {
        return (Module) Enum.valueOf(Module.class, str);
    }

    public static Module[] values() {
        return (Module[]) b.clone();
    }

    public ModuleType getType() {
        return this.f6102a;
    }
}
